version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ./schema_design/pg.env
    volumes:
      - ./schema_design/init.sql:/docker-entrypoint-initdb.d/init.sql
