version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ./schema_design/pg.env
    volumes:
      - ./schema_design/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

  celery:
    build: ./education_admin/
    command: celery -A config worker -l info
    volumes:
      - media:/media
    depends_on:
      - redis

  celery-beat:
    build: ./education_admin/
    command: celery -A config beat -l info
    depends_on:
      - redis

  education_app:
    build: ./education_admin/
    command: >
      bash -c "sleep 10
      && python manage.py migrate
      && python manage.py compilemessages
      && python manage.py add_permissions
      && python manage.py loaddata fixtures/users.json
      && python manage.py loaddata fixtures/education.json
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - media:/media
    depends_on:
      - db
      - redis

  nginx:
    restart: always
    image: nginx:latest
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
        - media:/media
        - ./nginx:/etc/nginx/conf.d
    depends_on:
        -   education_app

volumes:
  media:
